services:
  app:
    build: .
    container_name: crud_app
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://admin:secret@mongo:27017
      - REDIS_URI=redis:6379
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:latest
    container_name: go_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: godatabase
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
volumes:
  mongo_data:
